nelmio_api_doc:
    documentation:
        info:
            title: Bm furniture
            description: api for bm furniture shop
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api/v1