snc_redis:
    clients:
        default:
            type: predis
            alias: default
            dsn: '%env(REDIS_DSN)%'
        session:
            type: predis
            alias: session
            dsn: '%env(REDIS_DSN)%'